### ISSUE TITLE
ReferenceError: jQuery is not defined on fresh install

### ISSUE THREAD

**Issue by arcreative** [Anaphase/brunch-banana-pancakes#13]
Fresh install of this skeleton doesn't seem to include jQuery?  Is there something I'm doing wrong here? Using bower `1.3.12`, node `0.10.35`

The actual undefined reference is on bootstrap's `affix.js` jQuery injection.

I get this as well, but I don't think it hurts compilation:

```
> brunch watch --server
21 Jan 12:45:14 - error: { [Error: Component must have "/Users/adam/Downloads/new-app/bower_components/sizzle/bower.json"] code: 'NO_BOWER_JSON' }
21 Jan 12:45:14 - info: application started on http://localhost:3333/
21 Jan 12:45:15 - info: compiled 30 files and 1 cached into 6 files, copied 6 in 1002ms
```

**Comment by Anaphase** [comment]
Sizzle must have been removed as a dependency for the Bower jQuery component, so the manual override in brunch-banana-pancake's bower.json was causing install problems. Commit 89b4396 should fix this, try again!
